
# Starship Prompt Config for Robcio âœ¨
format = "$username@$hostname $directory $git_branch$git_status $nodejs $rust $package $cmd_duration $time $character"
add_newline = true

[directory]
truncation_length = 3
style = "cyan"

[git_branch]
symbol = "ðŸŒ± "
style = "purple"

[character]
success_symbol = "Î»"
error_symbol = "Î»"
style = "bold pink"

[username]
style_user = "bold green"

[hostname]
style = "dimmed white"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[time]
disabled = false
format = "ðŸ•’ [$time](dimmed white)"
